### ISSUE TITLE
Great code! But got a validation error

### ISSUE THREAD

**Issue by Rafkev** [parajukamal/weather#1]
Hi @parajukamal can you check

`/* Please check code line 7  apiUrl to be fetched is missing */
 const response = await fetch(apiUrl); `

**Comment by parajukamal** [comment]
Oh! thank you @Rafkev you are right. I still working on it.

**Comment by Rafkev** [comment]
Thought as much, but it is best you make your already tested and working project live. I hope to build on this soon. Cheers!

**Comment by parajukamal** [comment]
Thank you for updating. Hope we collaborate on bigger projects mate.
